# Generated by Django 5.1.5 on 2025-01-30 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authw', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privy_wallet_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_provider',
        ),
        migrations.CreateModel(
            name='UserWallets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255)),
                ('wallet_provider', models.CharField(choices=[('privy', 'Privy Wallet'), ('solflare', 'Solflare Wallet'), ('phanthom', 'Phanthom Wallet')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
