# Generated by Django 5.1.5 on 2025-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authw', '0004_remove_user_privy_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='credits_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='tiers',
            field=models.CharField(choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], default='tier1', max_length=10),
        ),
        migrations.AlterField(
            model_name='userwallets',
            name='wallet_provider',
            field=models.CharField(choices=[('privy', 'Privy Wallet'), ('solflare', 'Solflare Wallet'), ('phantom', 'Phantom Wallet')], max_length=50),
        ),
    ]
