# Generated by Django 5.1.5 on 2025-03-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authw', '0005_usersettings_credits_remaining_usersettings_tiers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='custom_themes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(default='system', max_length=20),
        ),
    ]
