# Generated by Django 5.1.5 on 2025-03-03 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authw', '0006_usersettings_custom_themes_alter_usersettings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='credits_remaining',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
    ]
