# Generated by Django 5.1.5 on 2025-03-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authw', '0006_usersettings_custom_themes_alter_usersettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile_pic',
            field=models.JSONField(default=dict),
        ),
    ]
