"""empty message

Revision ID: 1432da421028
Revises: 90dd7158eecd
Create Date: 2025-01-14 23:41:13.202141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1432da421028'
down_revision: Union[str, None] = '90dd7158eecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('privy_wallet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('wallet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'connect_wallet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('connect_wallet', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'wallet_id')
    op.drop_column('user', 'privy_wallet_id')
    # ### end Alembic commands ###
