"""empty message

Revision ID: b4a2e84c7ed5
Revises:
Create Date: 2025-01-14 22:53:42.999002

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4a2e84c7ed5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connect_wallet", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "wallet_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usersettings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "voice_preference", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "emotion_choices", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usersettings")
    op.drop_table("user")
    # ### end Alembic commands ###
