"""empty message

Revision ID: fe60ca4e6d61
Revises: 33087171498b
Create Date: 2025-01-19 15:16:49.392203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe60ca4e6d61'
down_revision: Union[str, None] = '33087171498b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'privy_wallet_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'wallet_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'wallet_provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersettings', 'theme',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersettings', 'voice_preference',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersettings', 'emotion_choices',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersettings', 'emotion_choices',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersettings', 'voice_preference',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersettings', 'theme',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'wallet_provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'wallet_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'privy_wallet_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
