# Generated by Django 5.1.5 on 2025-02-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='agent_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
