# Generated by Django 5.1.5 on 2025-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='message_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
